CREATE TABLE [dbo].[etiqueta](
	[etiquetaid] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [nvarchar](50) NOT NULL,
	[icono] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_etiqueta] PRIMARY KEY CLUSTERED 
(
	[etiquetaid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]